SHELL=/bin/bash

all: build clean

build:
	pdflatex -synctex=1 LernListe
	pdflatex -synctex=1 LernListe
	pdflatex -synctex=1 LernListe

clean:
	rm -f *.aux *.bbl *.blg *.glo *.idx *.log *.toc *.out *.synctex.gz

